version: '3.7'

services:

  cachelink_proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NGINX_IMAGE: ${NGINX_IMAGE:-nginx:1.25-alpine3.18-slim}
    volumes:
      - ./files/config-templates:/config-templates
      - ./example_env.env:/example_env.env
    env_file:
      - ./example_env.env
    ports:
      - "7777:7777"
      - "7778:7778"

  origin:
    build:
      context: ./files/dev/webserver
    ports:
      - "18080:8080"
